### ISSUE TITLE
login: No subscriptions were found for '***'.

### ISSUE THREAD

**Issue by bbenoist** [Azure/github-actions#59]
Hi!

I wanted to used the login action in my GitHub workflow but went to the following error (I'm still new to Azure):

```yml
      - name: Azure Login
        # TODO Remove once GitHub Actions supports job-wise conditions.
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: Azure/github-actions/login@master
        env:
          AZURE_SUBSCRIPTION: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
          AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
          AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
          AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}
```

```text
Run Azure/github-actions/login@master
 /usr/bin/docker run --name cee3f7d69da03ac78341a8b5eb85c30a146b5e_fd26e5 --label b3e3f7 --workdir /github/workspace --rm -e AZURE_SUBSCRIPTION -e AZURE_SERVICE_APP_ID -e AZURE_SERVICE_PASSWORD -e AZURE_SERVICE_TENANT -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/mencoder/mencoder":"/github/workspace" b3e3f7:d69da03ac78341a8aaeb85c30a146b5e
ERROR: No subscriptions were found for '***'. If this is expected, use '--allow-no-subscriptions' to have tenant level accesses
##[error]Docker run failed with exit code 1
```

On my machine, I've tried to `az login` then used the value of the `subscription` field returned by the `az account get-access-token` command but nothing has changed 😢 

How can I fix this the right way?

**Comment by thesattiraju** [comment]
Firstly, for actions-v2 we recommend you use this action for login: [`azure/actions/login@master`](https://github.com/Azure/actions/tree/master/login)

Could you ensure that the service principal you used in this flow has permissions on the subscription you've mentioned? You could follow this documentation to achieve that: [assign-the-application-to-a-role](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#assign-the-application-to-a-role)

>On my machine, I've tried to az login then used the value of the subscription field returned by the 
> az account get-access-token command but nothing has changed 😢

When you tried it on your machine, were you using your user credentials instead of this service principal credentials? If so, it is working as expected.
